# Generated by Django 5.1.7 on 2025-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_directions_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("u", "Unidades"),
                    ("g", "Gramos"),
                    ("kg", "Kilos"),
                    ("l", "Litros"),
                    ("ml", "Mililitros"),
                    ("tz", "Tazas"),
                    ("cdta", "Cucharaditas"),
                    ("cda", "Cucharadas"),
                    ("pz", "Pizca"),
                    ("oz", "Onzas"),
                    ("lb", "Libras"),
                ],
                default="gramos",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
