# Generated by Django 5.1.7 on 2025-03-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipeingredient_measurement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time_required",
            field=models.DurationField(),
        ),
    ]
