# Generated by Django 5.1.7 on 2025-03-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_time_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
