# Generated by Django 5.1.7 on 2025-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_image_alter_recipe_servings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time_required",
            field=models.TimeField(),
        ),
    ]
