# Generated by Django 5.1.7 on 2025-03-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_time_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time_required",
            field=models.DurationField(),
        ),
    ]
