# Generated by Django 5.1.7 on 2025-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_time_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("gr", "Gramos"),
                    ("kg", "Kilogramos"),
                    ("ml", "Mililitros"),
                    ("l", "Litros"),
                    ("tz", "Taza"),
                    ("cdta", "Cucharadita"),
                    ("cda", "Cucharada"),
                    ("u", "Unidad"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
