# Generated by Django 5.1.7 on 2025-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 estrella"),
                    (2, "2 estrellas"),
                    (3, "3 estrellas"),
                    (4, "4 estrellas"),
                    (5, "5 estrellas"),
                ]
            ),
        ),
    ]
