# Generated by Django 5.1.7 on 2025-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_userprofile_country_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
