# Generated by Django 5.1.7 on 2025-03-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_recipe_is_active_userprofile_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
