# Generated by Django 5.1.7 on 2025-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_tag_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
