# Generated by Django 5.1.7 on 2025-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_tag_tag_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("gr", "Gramo(s)"),
                    ("kg", "Kilogramo(s)"),
                    ("ml", "Mililitros"),
                    ("l", "Litro(s)"),
                    ("tz", "Taza(s)"),
                    ("cdta", "Cucharadita(s)"),
                    ("cda", "Cucharada(s)"),
                    ("u", "Unidad(es)"),
                    ("pizca", "Pizca(s)"),
                ],
                max_length=10,
            ),
        ),
    ]
