# Generated by Django 5.1.7 on 2025-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="images/recipes/default.jpg", upload_to="images/recipes/"
            ),
        ),
    ]
