# Generated by Django 5.1.7 on 2025-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_recipe_is_draft_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="measurement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gr", "Gramo(s)"),
                    ("kg", "Kilogramo(s)"),
                    ("ml", "Mililitros"),
                    ("l", "Litro(s)"),
                    ("tz", "Taza(s)"),
                    ("cdta", "Cucharadita(s)"),
                    ("cda", "Cucharada(s)"),
                    ("u", "Unidad(es)"),
                    ("pizca", "Pizca(s)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
