# Generated by Django 5.1.7 on 2025-05-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0023_alter_recipeingredient_measurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_draft",
        ),
    ]
