# Generated by Django 5.1.7 on 2025-05-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0024_remove_recipe_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredient",
            ),
        ),
    ]
